apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmms-api-pvc
  labels:
    app: cmms-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
